FROM java:8

VOLUME /tmp
ADD dockerTest.jar /opt/dockerTest/
EXPOSE 8080
WORKDIR /opt/dockerTest/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "dockerTest.jar"]
