FROM java:8

VOLUME /tmp
ADD docker-test.jar /opt/docker-test/
EXPOSE 8080
WORKDIR /opt/docker-test/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "docker-test.jar"]
